/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ExtensaoRouteImport } from './routes/extensao'
import { Route as GmnRouteImport } from './routes/gmn'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PromptsInstagramRouteImport } from './routes/prompts-instagram'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SistemasRouteImport } from './routes/sistemas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiProxyRouteImport } from './routes/api.proxy'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensaoRoute = ExtensaoRouteImport.update({
  id: '/extensao',
  path: '/extensao',
  getParentRoute: () => rootRouteImport,
} as any)
const GmnRoute = GmnRouteImport.update({
  id: '/gmn',
  path: '/gmn',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsInstagramRoute = PromptsInstagramRouteImport.update({
  id: '/prompts-instagram',
  path: '/prompts-instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasRoute = SistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/extensao': typeof ExtensaoRoute
  '/gmn': typeof GmnRoute
  '/instagram': typeof InstagramRoute
  '/mcp': typeof McpRoute
  '/membros': typeof MembrosRoute
  '/prompts': typeof PromptsRoute
  '/prompts-instagram': typeof PromptsInstagramRoute
  '/servicos': typeof ServicosRoute
  '/sistemas': typeof SistemasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/streaming': typeof StreamingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/proxy': typeof ApiProxyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/extensao': typeof ExtensaoRoute
  '/gmn': typeof GmnRoute
  '/instagram': typeof InstagramRoute
  '/mcp': typeof McpRoute
  '/membros': typeof MembrosRoute
  '/prompts': typeof PromptsRoute
  '/prompts-instagram': typeof PromptsInstagramRoute
  '/servicos': typeof ServicosRoute
  '/sistemas': typeof SistemasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/streaming': typeof StreamingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/proxy': typeof ApiProxyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/extensao': typeof ExtensaoRoute
  '/gmn': typeof GmnRoute
  '/instagram': typeof InstagramRoute
  '/mcp': typeof McpRoute
  '/membros': typeof MembrosRoute
  '/prompts': typeof PromptsRoute
  '/prompts-instagram': typeof PromptsInstagramRoute
  '/servicos': typeof ServicosRoute
  '/sistemas': typeof SistemasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/streaming': typeof StreamingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/proxy': typeof ApiProxyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/extensao'
    | '/gmn'
    | '/instagram'
    | '/mcp'
    | '/membros'
    | '/prompts'
    | '/prompts-instagram'
    | '/servicos'
    | '/sistemas'
    | '/sitemap.xml'
    | '/streaming'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/proxy'
    | '/blog/$slug'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/extensao'
    | '/gmn'
    | '/instagram'
    | '/mcp'
    | '/membros'
    | '/prompts'
    | '/prompts-instagram'
    | '/servicos'
    | '/sistemas'
    | '/sitemap.xml'
    | '/streaming'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/proxy'
    | '/blog/$slug'
    | '/blog'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/extensao'
    | '/gmn'
    | '/instagram'
    | '/mcp'
    | '/membros'
    | '/prompts'
    | '/prompts-instagram'
    | '/servicos'
    | '/sistemas'
    | '/sitemap.xml'
    | '/streaming'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/proxy'
    | '/blog/$slug'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ExtensaoRoute: typeof ExtensaoRoute
  GmnRoute: typeof GmnRoute
  InstagramRoute: typeof InstagramRoute
  McpRoute: typeof McpRoute
  MembrosRoute: typeof MembrosRoute
  PromptsRoute: typeof PromptsRoute
  PromptsInstagramRoute: typeof PromptsInstagramRoute
  ServicosRoute: typeof ServicosRoute
  SistemasRoute: typeof SistemasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StreamingRoute: typeof StreamingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiProxyRoute: typeof ApiProxyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensao': {
      id: '/extensao'
      path: '/extensao'
      fullPath: '/extensao'
      preLoaderRoute: typeof ExtensaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmn': {
      id: '/gmn'
      path: '/gmn'
      fullPath: '/gmn'
      preLoaderRoute: typeof GmnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts-instagram': {
      id: '/prompts-instagram'
      path: '/prompts-instagram'
      fullPath: '/prompts-instagram'
      preLoaderRoute: typeof PromptsInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas': {
      id: '/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof SistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ExtensaoRoute: ExtensaoRoute,
  GmnRoute: GmnRoute,
  InstagramRoute: InstagramRoute,
  McpRoute: McpRoute,
  MembrosRoute: MembrosRoute,
  PromptsRoute: PromptsRoute,
  PromptsInstagramRoute: PromptsInstagramRoute,
  ServicosRoute: ServicosRoute,
  SistemasRoute: SistemasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StreamingRoute: StreamingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiProxyRoute: ApiProxyRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
